// This file is auto-generated by @hey-api/openapi-ts

export { type Options, postApiGradesCalculate } from './sdk.gen';
export type { ClientOptions, LetterGrade, PostApiGradesCalculateData, PostApiGradesCalculateResponse, PostApiGradesCalculateResponses } from './types.gen';
