// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5034/' | (string & {});
};

export type LetterGrade = {
    gradePercentage?: number | string;
    letter?: string;
};

export type PostApiGradesCalculateData = {
    body: number | string;
    path?: never;
    query?: never;
    url: '/api/grades/calculate';
};

export type PostApiGradesCalculateResponses = {
    /**
     * OK
     */
    200: LetterGrade;
};

export type PostApiGradesCalculateResponse = PostApiGradesCalculateResponses[keyof PostApiGradesCalculateResponses];
